# Generated by Django 2.1.2 on 2018-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='고유ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='닉네임')),
            ],
        ),
    ]
