# Generated by Django 2.1.2 on 2018-10-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daliy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.MachineID', verbose_name='고유ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='시간')),
            ],
        ),
        migrations.AddField(
            model_name='daliy',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.TimeTable', verbose_name='시간'),
        ),
    ]
