# Generated by Django 2.1.2 on 2018-10-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181012_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daliy',
            new_name='Daily',
        ),
    ]
