# Generated by Django 2.1.2 on 2018-10-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181012_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='time',
            new_name='time_table',
        ),
    ]
