# Generated by Django 2.1.2 on 2018-10-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181013_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daily',
            unique_together={('date', 'time_table')},
        ),
    ]
