# Generated by Django 2.1.2 on 2018-10-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20181013_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='time_table',
            new_name='timetable',
        ),
        migrations.AlterUniqueTogether(
            name='daily',
            unique_together={('date', 'timetable')},
        ),
    ]
